name: Test Multiple Python Versions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.12
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: Format code with Python Black
        run: |
          make format
