name: Python application test with Github Actions
on: [push]
jobs:
  build:  
    runs-on: ubuntu-latest  
    steps:
    - name: Upgrade pip, setuptools, and wheel
      run: pip install --upgrade pip setuptools wheel wrapt pylint
    - uses: actions/checkout@v2
    - name: set up Python 3.12
    - uses: actions/setup-python@v4
      with:
       python-version: 3.12
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
